//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIGRANT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Migrante
    {
        public int IdEmigrante { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string TipoDocumento { get; set; }
        public int NumeroDocumento { get; set; }
        public string PaisOrigen { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string CorreoElectronico { get; set; }
        public string NumeroTelefono { get; set; }
        public string DireccionActual { get; set; }
        public string Ciudad { get; set; }
        public string SituacionLaboral { get; set; }
    }
}
